import { useEffect, useState } from 'react';
import { ArrowRight, Key, LockKey, SignOut, UserCircle } from '@phosphor-icons/react';
import { clearSession, del, getUser, patch, post } from '../client';
import { useData } from './data';
import { Shell } from './shell';
import { Button, DataTable, Input, Notice, PageHeader, Panel } from './components';
import { navigate } from './router';
import type { RecordValue } from './model';
export function AccountSettings() { const resource = useData<RecordValue>('/auth/me'); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); useEffect(() => { if (resource.data) { setFirstName(resource.data.firstName || ''); setLastName(resource.data.lastName || ''); } }, [resource.data]); return <Shell section="Account"><PageHeader kicker="Your identity" title="Account settings." description="Keep your profile and data under your control." /><Panel className="account-identity"><UserCircle size={48} /><div><strong>{resource.data?.email || getUser()?.email}</strong><small>{resource.data?.roles?.join(' · ') || getUser()?.roles.join(' · ')}</small></div></Panel><Panel className="narrow-panel"><div className="app-form-stack"><Input label="First name" value={firstName} onChange={setFirstName} /><Input label="Last name" value={lastName} onChange={setLastName} /><Button onClick={() => patch('/account', { firstName, lastName }).then(resource.reload)}>Save profile</Button></div></Panel><div className="settings-links"><button onClick={() => navigate('/account/security')}><LockKey size={21} /><span><strong>Security</strong><small>Password, MFA, active sessions</small></span><ArrowRight size={16} /></button><button onClick={() => navigate('/account/preferences')}><Key size={21} /><span><strong>Preferences</strong><small>Notifications and reminders</small></span><ArrowRight size={16} /></button></div></Shell>; }
export function PreferencesSettings() { const resource = useData<RecordValue>('/account/notification-preferences'); const [digest, setDigest] = useState('WEEKLY'); const [reminders, setReminders] = useState('true'); useEffect(() => { if (resource.data) { setDigest(resource.data.emailDigest || 'WEEKLY'); setReminders(String(resource.data.remindersEnabled ?? true)); } }, [resource.data]); return <Shell section="Preferences"><PageHeader kicker="Personal settings" title="Preferences." description="Tune how the platform keeps you informed." /><Panel className="narrow-panel"><div className="app-form-stack"><Input label="Email digest" value={digest} onChange={setDigest} /><Input label="Reminders enabled" value={reminders} onChange={setReminders} /><Button onClick={() => patch('/account/notification-preferences', { emailDigest: digest, remindersEnabled: reminders === 'true' }).then(resource.reload)}>Save preferences</Button></div></Panel></Shell>; }
export function SecuritySettings() { const resource = useData<RecordValue[]>('/account/sessions'); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [setup, setSetup] = useState<RecordValue | null>(null); const [notice, setNotice] = useState(''); return <Shell section="Security"><PageHeader kicker="Account protection" title="Security center." description="Protect access to your coaching workspace." /><div className="split-panels"><Panel><span className="app-kicker">Password</span><div className="app-form-stack"><Input label="New password" value={password} onChange={setPassword} type="password" /><Button onClick={() => patch('/account/password', { password }).then(() => setNotice('Password updated.'))}>Change password</Button></div><span className="app-kicker">Multi-factor authentication</span>{setup ? <div className="app-form-stack"><p>Secret: <strong>{setup.secret || setup.otpauthUrl}</strong></p><Input label="Authenticator code" value={code} onChange={setCode} /><Button onClick={() => post('/auth/mfa/confirm', { code }).then(() => setNotice('MFA enabled.'))}>Confirm MFA</Button></div> : <Button variant="secondary" onClick={() => post<RecordValue>('/auth/mfa/setup').then(setSetup)}>Set up MFA</Button>}<Button variant="ghost" onClick={() => post('/auth/mfa/disable').then(() => setNotice('MFA disabled.'))}>Disable MFA</Button>{notice && <Notice>{notice}</Notice>}</Panel><Panel><span className="app-kicker">Active sessions</span><DataTable columns={['Device', 'Last seen', '']} rows={(resource.data || []).map((session) => [session.userAgent || 'Current browser', session.lastSeenAt ? new Date(session.lastSeenAt).toLocaleString() : 'Active', <button className="app-row-action" key="revoke" onClick={() => del(`/account/sessions/${session.id}`).then(resource.reload)}><SignOut size={16} /></button>])} /></Panel></div><Button variant="danger" onClick={() => { if (window.confirm('Deactivate this account?')) void del('/account').then(() => { clearSession(); navigate('/'); }); }}>Delete account</Button></Shell>; }
