import { FormEvent, useState } from 'react';
import { ArrowRight, Check, Key, UserPlus } from '@phosphor-icons/react';
import { patch, post } from '../client';
import { useData, formatMoney } from './data';
import { Shell } from './shell';
import { Button, DataTable, Input, Notice, PageHeader, Panel } from './components';
import { navigate } from './router';
import { PaymentCheckout } from './contract-pages';
import type { RecordValue } from './model';
export function PasswordResetComplete() { const [token, setToken] = useState(''); const [password, setPassword] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); return <main className="auth-new"><div className="auth-new-aside"><span className="app-kicker">Account recovery</span><h1>Choose a new password.</h1><p>Use the token from your reset email. Passwords are never stored in the browser.</p></div><form className="auth-new-card" onSubmit={async (event) => { event.preventDefault(); setError(''); try { await post('/auth/password-reset/reset', { token, password }, { auth: false }); setNotice('Password updated. You can sign in now.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Reset failed'); } }}><span className="app-kicker">Reset access</span><Input label="Reset token" value={token} onChange={setToken} /><Input label="New password" value={password} onChange={setPassword} type="password" /><Button type="submit">Set password <ArrowRight size={16} /></Button>{error && <Notice tone="error">{error}</Notice>}{notice && <Notice>{notice}</Notice>}<Button variant="ghost" onClick={() => navigate('/login')}>Back to sign in</Button></form></main>; }
export function PurchaseCourse({ courseId }: { courseId: string }) { const resource = useData<RecordValue>(`/learning/courses/${courseId}`); const course = resource.data; return <Shell section="Course purchase"><PageHeader kicker="Course access" title={course?.title || 'Course'} description={course?.description} /><PaymentCheckout courseId={courseId} priceCents={course?.priceCents || 0} /><Panel><span className="app-kicker">What you receive</span><div className="lesson-list">{(course?.modules || []).map((module: RecordValue) => <div className="module-row" key={module.id}><span><strong>{module.title}</strong><small>{module.lessons?.length || 0} lessons</small></span></div>)}</div></Panel></Shell>; }
export function PeopleContract() { const resource = useData<RecordValue[]>('/users'); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('STUDENT'); const [notice, setNotice] = useState(''); return <Shell section="People"><PageHeader kicker="Tenant operations" title="People directory." description="Create accounts with the complete admin user contract." /><Panel><form className="app-form-grid" onSubmit={async (event) => { event.preventDefault(); await post('/auth/users', { firstName, lastName, email, password, role }); setNotice('User created.'); setFirstName(''); setLastName(''); setEmail(''); setPassword(''); resource.reload(); }}><Input label="First name" value={firstName} onChange={setFirstName} /><Input label="Last name" value={lastName} onChange={setLastName} /><Input label="Email" value={email} onChange={setEmail} type="email" /><Input label="Temporary password" value={password} onChange={setPassword} type="password" /><Input label="Role" value={role} onChange={setRole} /><Button type="submit"><UserPlus size={16} /> Create account</Button></form>{notice && <Notice>{notice}</Notice>}</Panel><div className="spacer-18" /><DataTable columns={['Name', 'Email', 'Status', 'Action']} rows={(resource.data || []).map((person) => [<strong key="name">{person.firstName} {person.lastName}</strong>, person.email, person.status, <button className="app-row-action" key="status" onClick={() => patch(`/users/${person.id}`, { status: person.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE' }).then(resource.reload)}><Check size={16} /></button>])} /></Shell>; }
export function ThemeLibraryContract() { const resource = useData<RecordValue[]>('/tenant/themes'); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [tokenJson, setTokenJson] = useState('{"accent":"#9184d9","radius":"8px"}'); const [selected, setSelected] = useState<RecordValue | null>(null); return <Shell section="Themes" admin><PageHeader kicker="Design system" title="Theme library." description="Theme records include the complete token JSON required by the backend." /><Panel><form className="app-form-stack" onSubmit={async (event) => { event.preventDefault(); await post('/tenant/themes', { name, description, tokenJson: JSON.parse(tokenJson) }); setName(''); setDescription(''); resource.reload(); }}><Input label="Theme name" value={name} onChange={setName} /><Input label="Description" value={description} onChange={setDescription} /><label className="app-field"><span>Token JSON</span><textarea value={tokenJson} onChange={(event) => setTokenJson(event.target.value)} rows={8} /></label><Button type="submit">Create theme</Button></form></Panel><div className="spacer-18" /><DataTable columns={['Theme', 'Description', 'Status', 'Edit']} rows={(resource.data || []).map((item) => [<strong key="name">{item.name}</strong>, item.description, item.isActive ? 'Active' : 'Archived', <button className="app-row-action" key="edit" onClick={() => setSelected(item)}><Key size={16} /></button>])} />{selected && <Panel><span className="app-kicker">Edit theme</span><Button onClick={() => patch(`/tenant/themes/${selected.id}`, { name: selected.name, description: selected.description, tokenJson: selected.tokenJson || {} }).then(() => { setSelected(null); resource.reload(); })}>Save theme <Check size={16} /></Button></Panel>}</Shell>; }
