import { ReactNode } from 'react';
import { Check, CircleNotch, MagnifyingGlass, Sparkle, WarningCircle } from '@phosphor-icons/react';
export function Button({ children, onClick, type = 'button', variant = 'primary', disabled = false }: { children: ReactNode; onClick?: () => void; type?: 'button' | 'submit'; variant?: string; disabled?: boolean }) { return <button type={type} className={`app-button app-button-${variant}`} onClick={onClick} disabled={disabled}>{children}</button>; }
export function Input({ label, value, onChange, type = 'text', placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="app-field"><span>{label}</span><input value={value} type={type} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }
export function PageHeader({ kicker, title, description, actions }: { kicker: string; title: string; description?: string; actions?: ReactNode }) { return <header className="app-page-header"><div><span className="app-kicker">{kicker}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="app-actions">{actions}</div>}</header>; }
export function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`app-panel ${className}`}>{children}</section>; }
export function Stat({ label, value, detail, accent = false }: { label: string; value: string | number; detail?: string; accent?: boolean }) { return <div className={`app-stat ${accent ? 'is-accent' : ''}`}><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>; }
export function Empty({ title, description }: { title: string; description: string }) { return <div className="app-empty"><Sparkle size={24} /><strong>{title}</strong><span>{description}</span></div>; }
export function Loading() { return <div className="app-loading"><CircleNotch className="spin" size={20} /> Loading workspace</div>; }
export function ErrorState({ message }: { message: string }) { return <div className="app-error"><WarningCircle size={20} />{message}</div>; }
export function DataTable({ columns, rows }: { columns: string[]; rows: ReactNode[][] }) { return <div className="app-table-wrap"><table className="app-table"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>) : <tr><td colSpan={columns.length}><Empty title="Nothing here yet" description="Your next useful step will appear here." /></td></tr>}</tbody></table></div>; }
export function SearchBox({ value, onChange, placeholder = 'Search' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="app-search"><MagnifyingGlass size={17} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }
export function Notice({ children, tone = 'success' }: { children: ReactNode; tone?: 'success' | 'error' }) { return <div className={`app-notice app-notice-${tone}`}>{tone === 'success' ? <Check size={17} /> : <WarningCircle size={17} />}{children}</div>; }
